FROM quay.io/fedora/fedora:latest
MAINTAINER Niranjan MR <mrniranjan@fedoraproject.org>
LABEL version="1.0"

# install packages
RUN dnf clean all && \
    dnf install -y wget bash git emacs ShellCheck git vim-enhanced golang-bin golang pre-commit patch

ENV GOPATH /root/go
ENV GOBIN $GOPATH/bin
ENV PATH $GOBIN:$PATH

# create emacs directories
RUN mkdir -p ~/.emacs.d/lisp \
    mkdir  ~/.emacs.d/backup

# install ginkgo and gomega
RUN go install github.com/onsi/ginkgo/v2/ginkgo@latest && \
    go install github.com/onsi/gomega@latest; exit 0

# install gopls
RUN go install golang.org/x/tools/gopls@latest

# copy basic configuration
COPY init.el /root/.emacs.d/init.el

# copy lsp mode configuration
COPY lsp.el /root/.emacs.d/lisp/lsp.el

# Install emacs packages
RUN emacs --batch -l /root/.emacs.d/init.el
